# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 986b3a5c6e11275174dea47b27ec65fd59377e1b0d5ffec36b5e6311ec1d455a8af448ebac13229bce4d426c1374fbf626313e7e0653f73a9b9218e3a989b678

test:
  secret_key_base: 9ca481c5436954a8092a105e0090313ec8b97e1dae2760023311ce67dfb1083e2633cc4b4ad2e7da6834be986a4c72076c18eb079b396a9da1535943ee5bc246

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
